[package]
name = "ising"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
plotters = "0.3.7"
rand = { version = "0.8.5", features = ["small_rng"] }

[[bench]]
name = "my_benchmark"
harness = false
